### ISSUE TITLE
[QA] identifiere-registration.yml setting trusted:true has no effect

### ISSUE THREAD

**Issue by jnweiger** [owncloud/openidconnect#105]
Tested with server 10.5 + openidconnect 1.0.0RC4 for owncloud/openidconnect#66 + desktop client testpilotcloud version 2.7.0daily20201004 (build 2209)

My kopano/konnect/konnectd-identifier-registration.yaml contains
```
---
# OpenID Connect client registry.
clients:
  - id: ownCloud
    secret: ownCloud
    application_type: web
    insecure: true

  - id: xdXOt13JKxym1B1QcEncf2XDkLAexMBFwiT9j6EfhhHFJhs2KM9jbjTmf8JBXE69
    secret: UBntmLjC2yYCeHwsyj73Uwo9TAaecAetRwMw0xYcvNL9yRdLSUi0hUAHfvCHFeFh
    name: ownCloud desktop client
    application_type: native
    insecure: true
    trusted: true

```
...

![image](https://user-images.githubusercontent.com/1108546/95431487-839a6e80-094d-11eb-87a6-61528211b02c.png)

The `name:` element is effective (I change the exact spelling of the name to verifiy that I am editing the correct identifier-registration.yaml file.)
The `trusted:` element is not.

Expected behaviour: Because of `trusted: true`, the above shown dialog should be skipped. The client should recieve permission without extra user interaction.
